include:
  - project: 'gnome/citemplates'
    file: 'flatpak/flatpak-ci-initiative-sdk-extensions.yml'
    # ref: ''
  - component: "gitlab.gnome.org/GNOME/citemplates/basic-release-with-dist@25.4"
    inputs:
      dist-job-name: "flatpak"

stages:
  - check
  - test
  - deploy

flatpak:
  extends: ".flatpak"
  variables:
    APP_ID: "io.github.workbydivyanshu.Aubade.Devel"
    BUNDLE: "io.github.workbydivyanshu.Aubade.Devel.flatpak"
    FLATPAK_MODULE: "aubade"
    MANIFEST_PATH: "io.github.workbydivyanshu.Aubade.json"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"

rust-fmt:
  image: "rust:slim"
  stage: "check"
  needs: []
  script:
    - rustup component add rustfmt
    - echo -e "" > src/config.rs
    - rustc -Vv && cargo -Vv
    - cargo --version
    - cargo fmt --all -- --check

reuse:
  image: fedora:latest
  stage: "check"
  needs: []
  before_script:
    - export PATH="$HOME/.local/bin:$PATH"
    - dnf install -y python3-pip
  script:
    - pip install --user reuse
    - reuse lint
