"""Aubade — shared types and protocols."""
from __future__ import annotations
from dataclasses import dataclass
from typing import Protocol
from pathlib import Path


# Track is owned by library.py — the app's single source of truth. It is a
# MUTABLE dataclass (library._read_tags fills in tags after construction) and
# carries `playable`, which player.Engine.set_queue filters on. Do not redefine
# it here; re-export it so new modules can import from one place.
from .library import Track  # noqa: E402,F401  (re-export)


@dataclass(frozen=True, slots=True)
class AlbumInfo:
    album: str
    artist: str
    count: int
    year: int = 0
    art_path: str | None = None


@dataclass(frozen=True, slots=True)
class ArtistInfo:
    artist: str
    tracks: int
    plays: int
    albums: int = 0


class LibraryBackend(Protocol):
    """Local library operations — no network, just SQLite cache."""

    def all_tracks(self) -> list[Track]: ...
    def tracks_for_artist(self, artist: str) -> list[Track]: ...
    def tracks_for_album(self, album: str, artist: str) -> list[Track]: ...
    def tracks_for_genre(self, genre: str) -> list[Track]: ...
    def albums(self) -> list[AlbumInfo]: ...
    def artists(self) -> list[ArtistInfo]: ...
    def all_genres(self, limit: int | None = None) -> list[tuple[str, int]]: ...
    def top_genres(self, limit: int) -> list[tuple[str, int]]: ...
    def top_artist(self) -> tuple[str, int, int] | None: ...
    def liked_tracks_list(self) -> list[Track]: ...
    def most_played_tracks(self, limit: int) -> list[Track]: ...
    def recent_added(self, limit: int) -> list[Track]: ...
    def recent_plays(self, limit: int) -> list[dict]: ...
    def all_plays(self, limit: int) -> list[dict]: ...
    def first_track_path(self, album: str, artist: str) -> str | None: ...
    def set_like(self, path: str, liked: bool) -> None: ...
    def record_play(self, path: str) -> None: ...
    def record_skip(self, path: str) -> None: ...
    def clear_plays(self) -> None: ...
    def counts(self) -> dict: ...
    def get_profile(self, key: str, default: str = "") -> str: ...
    def set_profile(self, key: str, value: str) -> None: ...
    def liked_paths(self) -> set[str]: ...


class PlaybackEngine(Protocol):
    """GStreamer playback — local files only."""

    @property
    def playing(self) -> bool: ...
    @property
    def queue(self) -> list[Track]: ...
    @property
    def index(self) -> int: ...

    def current(self) -> Track | None: ...
    def position(self) -> float: ...
    def duration(self) -> float: ...
    def set_queue(self, tracks: list[Track], start_index: int) -> None: ...
    def play_index(self, i: int) -> None: ...
    def toggle(self) -> None: ...
    def next(self) -> None: ...
    def prev(self) -> None: ...
    def seek_frac(self, frac: float) -> None: ...
    def set_volume(self, v: float) -> None: ...
    @property
    def volume(self) -> float: ...
    def set_shuffle(self, on: bool) -> None: ...
    @property
    def shuffle(self) -> bool: ...
    def set_repeat_mode(self, mode: str) -> None: ...
    def repeat_mode(self) -> str: ...
    def toggle_repeat(self) -> None: ...
    def shutdown(self) -> None: ...


# ---------- Art cache ----------

def thumb_for(path: str, size: int) -> str | None:
    """Return cached thumbnail path or None."""
    from .art import thumb_for as _thumb_for
    return _thumb_for(path, size)